services:
  discservice:
    image: discservice
    build:
      context: .
      dockerfile: DiscService/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=disc-db;Port=5432;User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Database=${POSTGRES_DB};
      - KafkaSettings__BootstrapServers=${KAFKA_BOOTSTRAP_SERVERS}
    depends_on:
      disc-db:
        condition: service_healthy
    networks:
      - command-manager-network

  disc-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - disc-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}' ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - command-manager-network

volumes:
  disc-db-data:

networks:
  command-manager-network:
    external: true
